### ISSUE TITLE
Flush all buckets, regardless of trigger (eg after a request)

### ISSUE THREAD

**Issue by glittershark** [oliyh/superlifter#14]
My initial use of superlifter in my application has run into a *number* of hard-to-track-down cases of requests stalling in certain cases, but not in other cases, even in cases where I'm using interval triggers alongside count triggers - to the point where I've actually reverted it in my application because I was spending multiple hours trying to track down these stalls. 

To prevent this from happening (or at least mitigate it somewhat) I think it'd be nice to have the ability to flush *all* buckets, regardless of their triggers, which could be called at the end of eg Lacinia processing a request. This also obviously relies on depth-first vs breadth-first behavior, but would be a nice tool to have in the toolbox regardless

**Comment by oliyh** [comment]
Hello,
There is an API function for this, see https://github.com/oliyh/superlifter/blob/ded9eef3b0db9af07962583934a7e3f4c126777a/src/superlifter/api.cljc#L53

Also be aware of #12 which I haven't quite tracked down yet. Are you performing parallel queries too?

Thanks for your bug reports. Superlifter is still quite new so I appreciate the feedback.

Thanks

**Comment by glittershark** [comment]
Ah, cool. I wonder if adding that to the pedestal interceptor for use with lacinia would work?

**Comment by glittershark** [comment]
I am performing parallel queries too, but haven't run into #12 yet. I wonder if it has something to do with the fact that bucket triggers and queues are separate atoms (perhaps there's some kind of race?). Maybe making those Refs to coordinate the state somewhat like I mentioned in #13 would help.

**Comment by oliyh** [comment]
I don't think it would be possible for lacinia to complete and start returning down the pedestal interceptor chain with any fetches left inside superlifter, because it wouldn't complete until they had been delivered.

I'm wondering if your PR #15 will give any more insight into #12, at least it might confirm it is happening.

**Comment by oliyh** [comment]
Hi, I'm closing this as subsequent work around hanging should have addressed this. There is a (hopefully) final piece of the puzzle coming in #27 in the case where your fetches are failing completely. Please feel free to reopen if there's something I've missed.

Cheers
