### ISSUE TITLE
Missing dependency to pedestal

### ISSUE THREAD

**Issue by mokshasoft** [oliyh/superlifter#21]
The superlifter.lacinia namespace uses io.pedestal.interceptor, but the dependency to io.pedestal/pedestal.interceptor is missing in project.clj.

My namespace requires superlifter.lacinia, but doesn't use pedestal directly, therefore I get a dependency problem.

**Comment by oliyh** [comment]
Hi,

This is intentional to avoid dependency conflicts and/or dragging in lacinia for those who wish to use superlifter without lacinia or are using it for cljs only. It's expected that if you wish to use superlifter with lacinia that you already have lacinia set up in your project.

**Comment by mokshasoft** [comment]
Ok, thanks for the explanation.

**Comment by xiongtx** [comment]
[Lacinia](https://github.com/walmartlabs/lacinia) is not necessarily tied to Pedestal:

> This library can be plugged into any Clojure HTTP pipeline. The companion library [lacinia-pedestal](https://github.com/walmartlabs/lacinia-pedestal) provides full HTTP support, including GraphQL subscriptions, for [Pedestal](https://github.com/pedestal/pedestal).

We're using Lacinia & Superlifter w/out Pedestal, & find ourselves re-implementing `with-superlifter` b/c we don't have the Pedestal dependency. Not a big deal, but it'd be nice if Lacinia & Pedestal weren't conflated.
